
version: '2.1'

orbs:
  python: circleci/python@2.1.1

workflows:
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

jobs:
  build:
    docker:
      - image: cimg/python:3.12-browsers
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install library dependencies
          command: |
            sudo apt update
            sudo apt install libnotify-dev
            sudo apt install libgtk-3-dev
            sudo apt-get install -y  libsdl2-dev
            pip install --upgrade pip
            pip install wheel
            pip install setuptools
            pip install codeallybasic==1.9.0
            pip install pyutmodelv2==2.2.2
            pip install ogl==3.6.4
            pip install untanglepyut>=2.6.3
      - run:
            name: run tests
            command: | 
              pip install buildlackey
              unittests
