
version: '2.1'

orbs:
  python: circleci/python@2.1.1

workflows:
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

jobs:
  build:
    docker:
      - image: cimg/python:3.12-browsers
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install library dependencies
          command: |
            pip install --upgrade pip
            pip install wheel
            pip install setuptools
            pip install'PyGithub==2.5.0
            pip install click==8.1.6
            pip install'codeallybasic==1.9.0

      - run:
            name: run tests
            command: | 
              pip install buildlackey
              unittests
